### ISSUE TITLE
FP issues

### ISSUE THREAD

**Issue by LebedevRI** [rutgers-apl/alive-nj#16]
I guess this may be related to #14, and may be a sign of some larger issue.

```
----------                                                                      
Name: sitofp i32 -> float, eq
Pre: width(C) u< 32
  %f   = sitofp i32 %i to float
  %b   = bitcast float %f to i32
  %cmp = icmp eq i32 %b, C
=>
  %cmp = icmp eq i32 %i, C

Done: 1                                                                         
Optimization is correct
```

If `%i` is `1`, that means `%b` is [`0x3f800000`](https://www.h-schmidt.net/FloatConverter/IEEE754.html)...
Since the `C` is the same constant in both cases, it can't be `1` and `0x3f800000` at the same time,
so this transform should not be valid for `%i`=`1`.

Am i somehow not telling it that the `C` is the bitwise exact the same on the both sides of the `=>`?

**Comment by davemenendez** [comment]
What's happening here is that the precondition is unsatisfiable. The type rules for Alive require C to be `i32`, but then the precondition will never be satisfied. If the precondition is removed, the transformation is rejected.

```
  %f   = sitofp i32 %i to float
  %b   = bitcast float %f to i32
  %cmp = icmp eq i32 %b, C
=>
  %cmp = icmp eq i32 %i, C

ERROR: Mismatch in values for i1 %cmp                                           

Example:
  i32 %i = 0xfff4fffc (4294246396, -720900)
float %f = -1.37500762939453125*(2**19)
  i32 %b = 0x89b00040 (2310012992, -1984954304)
  i32 C  = 0xfff4fffc (4294246396, -720900)
source: 0x0 (0)
target: 0x1 (1, -1)
```

For what it's worth, warning about unsatisfiable preconditions has been on my to-do list for a while.

**Comment by LebedevRI** [comment]
That's a rather huge pitfall :)
